

const char phrase1[] PROGMEM =  "您好，我们是无声咖啡师";
const char phrase2[] PROGMEM =  "您好，很高兴为您服务";
const char phrase3[] PROGMEM =  "请问您想喝热的还是冰的？";
const char phrase4[] PROGMEM =  "我用AR翻译眼镜和你交流";
const char phrase5[] PROGMEM =  "好的没问题";
const char phrase6[] PROGMEM =  "很抱歉，可能不行";
const char phrase7[] PROGMEM =  "很高兴为您服务";
const char phrase8[] PROGMEM =  "请问还有什么要求吗？";
const char phrase9[] PROGMEM =  "这是咖啡店的菜单，请您过目";
const char phrase10[] PROGMEM =  "请您再说一次 谢谢 我没听清楚";
const char phrase11[] PROGMEM =  "可以扫码小程序点单";
const char phrase12[] PROGMEM =  "如果你纠结点单，我来推荐好吗？";
const char phrase13[] PROGMEM =  "这款晴天绿薄荷店里很不错";
const char phrase14[] PROGMEM =  "可以试如果您不确定要喝什么咖啡";
const char phrase15[] PROGMEM =  "请问您需要我帮您推荐一款吗？";
const char phrase16[] PROGMEM =  "如果您喜欢浓郁的口感";
const char phrase17[] PROGMEM =  "我们店招牌是冠军拿铁哦";
const char phrase18[] PROGMEM =  "您想点什么咖啡饮品还是面包？";
const char phrase19[] PROGMEM =  "面包有三种";
const char phrase20[] PROGMEM =  "可颂、葡萄卷、柠檬贝果";
const char phrase21[] PROGMEM =  "面包需要加热吗";
const char phrase22[] PROGMEM =  "请问您要喝咖啡还是茶？";
const char phrase23[] PROGMEM =  "除了咖啡我们还有茶和果汁";
const char phrase24[] PROGMEM =  "还有喜欢吗？";
const char phrase25[] PROGMEM =  "谢谢光临";
const char phrase26[] PROGMEM =  "需要打包吗";
const char phrase27[] PROGMEM =  "奈娃爱您！";
const char phrase28[] PROGMEM =  "爪爪爱您！";
const char phrase29[] PROGMEM =  "我能帮您推荐吗";
const char phrase30[] PROGMEM =  "绿柠茶冰冰";
const char phrase31[] PROGMEM =  "菠莓茶冰冰";
const char phrase32[] PROGMEM =  "日落躺岛";
const char phrase33[] PROGMEM =  "星愿湾椰椰拿铁推荐全冰";
const char phrase34[] PROGMEM =  "小镇燕麦拿铁";
const char phrase35[] PROGMEM =  "晴空山巴旦木拿铁";
const char phrase36[] PROGMEM =  "晴空山核桃拿铁";
const char phrase37[] PROGMEM =  "橙咖橘子海有咖啡";
const char phrase38[] PROGMEM =  "整块蜂巢麦奇朵，有一颗蜂巢呢";
const char phrase39[] PROGMEM =  "晴天薄荷绿";
const char phrase40[] PROGMEM =  "不喜欢咖啡，可以考虑奶猪古力";
const char phrase41[] PROGMEM =  "奶猪燕麦";
const char phrase42[] PROGMEM =  "推荐三杯小奈咖";
const char phrase43[] PROGMEM =  "小岛绿薄荷";
const char phrase44[] PROGMEM =  "吵够了莓";
const char phrase45[] PROGMEM =  "头上有点绿";
const char phrase46[] PROGMEM =  "挚爱冠军拿铁";
const char phrase47[] PROGMEM =  "绝美美式";
const char phrase48[] PROGMEM =  "小美美式";
const char phrase49[] PROGMEM =  "热还是冷？";
const char phrase50[] PROGMEM =  "温热？";
const char phrase51[] PROGMEM =  "您需要加糖吗？";
const char phrase52[] PROGMEM =  "正常冰？少冰？去冰？";
const char phrase53[] PROGMEM =  "少糖？正常糖？无糖？";
const char phrase54[] PROGMEM =  "无糖，不推荐。推荐正常甜度";
const char phrase55[] PROGMEM =  "去冰，不推荐。推荐正常冰，好喝";
const char phrase56[] PROGMEM =  "喝前建议搅拌一下";
const char phrase57[] PROGMEM =  "建议大口大口喝";
const char phrase58[] PROGMEM =  "打包还是堂食？";
const char phrase59[] PROGMEM =  "MOMA燕麦奶是瑞典进口的健康奶";
const char phrase60[] PROGMEM =  "这是您的小票，请收好。";
const char phrase61[] PROGMEM =  "谢谢您！";
const char phrase62[] PROGMEM =  "再见，欢迎您再次光临";
const char phrase63[] PROGMEM =  "祝你用餐愉快";
const char phrase64[] PROGMEM =  "请稍等一下";
const char phrase65[] PROGMEM =  "使用员工券 请扫会员码";
const char phrase66[] PROGMEM =  "您的订单马上就好，请稍等片刻";
const char phrase67[] PROGMEM =  "您的咖啡已经准备好，请您慢用";
const char phrase68[] PROGMEM =  "咖啡很热，小心烫";
const char phrase69[] PROGMEM =  "咖啡是醒神的好帮手";
const char phrase70[] PROGMEM =  "会有一个美好的一天";
const char phrase71[] PROGMEM =  "洗手间在对面的酒店";
const char phrase72[] PROGMEM =  "咖啡太热，我可以给您加点冰块";
const char phrase73[] PROGMEM =  "我们还有蛋糕和面包搭配咖啡";
const char phrase74[] PROGMEM =  "我们的咖啡是我们自己种的哦";
const char phrase75[] PROGMEM =  "这边请";
const char phrase76[] PROGMEM =  "没关系";
const char phrase77[] PROGMEM =  "不用谢";
const char phrase78[] PROGMEM =  "不客气";
const char phrase79[] PROGMEM =  "我想想办法，看看怎样帮您";
const char phrase80[] PROGMEM =  "请稍等一下，我去请示一下店长";
const char phrase81[] PROGMEM =  "对不起，我没有听清楚";
const char phrase82[] PROGMEM =  "请您重复一遍，好吗？";
const char phrase83[] PROGMEM =  "没问题";
const char phrase84[] PROGMEM =  "再见 感恩您的光临";
const char phrase85[] PROGMEM =  "谢谢你，下次再来";
const char phrase86[] PROGMEM =  "让您久等了，感谢您的耐心等待";
const char phrase87[] PROGMEM =  "麻烦您留一下您的联系电话";
const char phrase88[] PROGMEM =  "请带好随身物品";
const char phrase89[] PROGMEM =  "牛奶是全脂牛奶不是低脂牛奶";
const char phrase90[] PROGMEM =  "请稍候，我马上为您安排";
const char phrase91[] PROGMEM =  "谢谢，欢迎您再来。";
const char phrase92[] PROGMEM =  "谢谢慢走，祝您生活愉快";
const char phrase93[] PROGMEM =  "请告诉我们您的意见和建议";
const char phrase94[] PROGMEM =  "我们会不断改进";
const char phrase95[] PROGMEM =  "我们的咖啡豆都是新鲜烘焙的";
const char phrase96[] PROGMEM =  "咖啡因有助于提高注意力和记忆力";
const char phrase97[] PROGMEM =  "谢谢您，祝您今天愉快！";
const char phrase98[] PROGMEM =  "关注我们";
const char phrase99[] PROGMEM =  "获取更多咖啡知识和独家优惠信息";
const char phrase100[] PROGMEM =  "会员优惠福利";
const char phrase101[] PROGMEM =  "成为我们的会员";
const char phrase102[] PROGMEM =  "您将享受到更多的优惠和专属福利";
const char phrase103[] PROGMEM =  "会员每月都有机会获得免费咖啡券";
const char phrase104[] PROGMEM =  "在会员日";
const char phrase105[] PROGMEM =  "您还可以享受到买一赠一的优惠";
const char phrase106[] PROGMEM =  "参与我们的线上互动活动";
const char phrase107[] PROGMEM =  "有机会赢取精美礼品";
const char phrase108[] PROGMEM =  "我们的咖啡豆都是我们自己种的哦";
const char phrase109[] PROGMEM =  "为给您带来最完美的咖啡";
const char phrase110[] PROGMEM =  "我们坚持使用最新鲜的咖啡豆";
const char phrase111[] PROGMEM =  "确保每一杯咖啡都充满生命力";
const char phrase112[] PROGMEM =  "咖啡不仅味道好";
const char phrase113[] PROGMEM =  "健康益处如提高注意力、抗氧化等";
const char phrase114[] PROGMEM =  "咖啡采用低糖、低脂配方";
const char phrase115[] PROGMEM =  "也能保持健康";
const char phrase116[] PROGMEM =  "适量饮用咖啡";
const char phrase117[] PROGMEM =  "可以降低患糖尿病的风险";
const char phrase118[] PROGMEM =  "让您的生活更加健康";
const char phrase119[] PROGMEM =  "您好，杯子给我帮您丢掉";
const char phrase120[] PROGMEM =  "这个装置还在测试，请您见谅谢谢";
const char phrase121[] PROGMEM =  "Cucumber Lemon Ice Tea";
const char phrase122[] PROGMEM =  "青瓜 柠檬 和 茉莉花茶";

const char* const phrases[] PROGMEM = {"",phrase1,phrase2,phrase3,phrase4,phrase5,phrase6,phrase7,phrase8,phrase9,phrase10,phrase11,phrase12,phrase13,phrase14,phrase15,phrase16,phrase17,phrase18,phrase19,phrase20,phrase21,phrase22,phrase23,phrase24,phrase25,phrase26,phrase27,phrase28,phrase29,phrase30,phrase31,phrase32,phrase33,phrase34,phrase35,phrase36,phrase37,phrase38,phrase39,phrase40,phrase41,phrase42,phrase43,phrase44,phrase45,phrase46,phrase47,phrase48,phrase49,phrase50,phrase51,phrase52,phrase53,phrase54,phrase55,phrase56,phrase57,phrase58,phrase59,phrase60,phrase61,phrase62,phrase63,phrase64,phrase65,phrase66,phrase67,phrase68,phrase69,phrase70,phrase71,phrase72,phrase73,phrase74,phrase75,phrase76,phrase77,phrase78,phrase79,phrase80,phrase81,phrase82,phrase83,phrase84,phrase85,phrase86,phrase87,phrase88,phrase89,phrase90,phrase91,phrase92,phrase93,phrase94,phrase95,phrase96,phrase97,phrase98,phrase99,phrase100,phrase101,phrase102,phrase103,phrase104,phrase105,phrase106,phrase107,phrase108,phrase109,phrase110,phrase111,phrase112,phrase113,phrase114,phrase115,phrase116,phrase117,phrase118,phrase119,phrase120,phrase121,phrase122,};
const int numberOfPhrases = 122;





/*
 PHRASES FROM 2024-4-14
const char phrase1[] PROGMEM = "您好，我们是无声咖啡师";
const char phrase2[] PROGMEM = "您好，很高兴为您服务";
const char phrase3[] PROGMEM = "请问您想喝热的还是冰的？";
const char phrase4[] PROGMEM = "我用AR翻译眼镜和你交流";
const char phrase5[] PROGMEM = "好的没问题";
const char phrase6[] PROGMEM = "很抱歉，可能不行";
const char phrase7[] PROGMEM = "很高兴为您服务";
const char phrase8[] PROGMEM = "请问还有什么要求吗？";
const char phrase9[] PROGMEM = "这是咖啡店的菜单，请您过目";
const char phrase10[] PROGMEM = "请您再说一次，谢谢，我没听清楚";
const char phrase11[] PROGMEM = "可以扫码小程序点单";
const char phrase12[] PROGMEM = "如果你纠结点单，我来推荐好吗？";
const char phrase13[] PROGMEM = "这款晴天绿薄荷店里很不错";
const char phrase14[] PROGMEM = "可以试如果您不确定要喝什么咖啡";
const char phrase15[] PROGMEM = "请问您需要我帮您推荐一款吗？";
const char phrase16[] PROGMEM = "如果您喜欢浓郁的口感";
const char phrase17[] PROGMEM = "我们店招牌是冠军拿铁哦";
const char phrase18[] PROGMEM = "您想点什么咖啡饮品还是面包？";
const char phrase19[] PROGMEM = "面包有三种";
const char phrase20[] PROGMEM = "可颂、葡萄卷、柠檬贝果";
const char phrase21[] PROGMEM = "面包需要加热吗";
const char phrase22[] PROGMEM = "请问您要喝咖啡还是茶？";
const char phrase23[] PROGMEM = "除了咖啡我们还有茶和果汁";
const char phrase24[] PROGMEM = "还有喜欢吗？";
const char phrase25[] PROGMEM = "谢谢光临";
const char phrase26[] PROGMEM = "需要打包吗";
const char phrase27[] PROGMEM = "奈娃爱您！";
const char phrase28[] PROGMEM = "爪爪爱您！";
const char phrase29[] PROGMEM = "我能帮您推荐吗";
const char phrase30[] PROGMEM = "绿柠茶冰冰";
const char phrase31[] PROGMEM = "菠莓茶冰冰";
const char phrase32[] PROGMEM = "日落躺岛";
const char phrase33[] PROGMEM = "星愿湾椰椰拿铁推荐全冰";
const char phrase34[] PROGMEM = "小镇燕麦拿铁";
const char phrase35[] PROGMEM = "晴空山巴旦木拿铁";
const char phrase36[] PROGMEM = "晴空山核桃拿铁";
const char phrase37[] PROGMEM = "橙咖橘子海有咖啡";
const char phrase38[] PROGMEM = "整块蜂巢麦奇朵，有一颗蜂巢呢";
const char phrase39[] PROGMEM = "晴天薄荷绿";
const char phrase40[] PROGMEM = "不喜欢咖啡，可以考虑奶猪古力";
const char phrase41[] PROGMEM = "奶猪燕麦";
const char phrase42[] PROGMEM = "推荐三杯小奈咖";
const char phrase43[] PROGMEM = "小岛绿薄荷";
const char phrase44[] PROGMEM = "吵够了莓";
const char phrase45[] PROGMEM = "头上有点绿";
const char phrase46[] PROGMEM = "挚爱冠军拿铁";
const char phrase47[] PROGMEM = "绝美美式";
const char phrase48[] PROGMEM = "小美美式";
const char phrase49[] PROGMEM = "热还是冷？";
const char phrase50[] PROGMEM = "温热？";
const char phrase51[] PROGMEM = "您需要加糖吗？";
const char phrase52[] PROGMEM = "正常冰？少冰？去冰？";
const char phrase53[] PROGMEM = "少糖？正常糖？无糖？";
const char phrase54[] PROGMEM = "无糖，不推荐。推荐正常甜度";
const char phrase55[] PROGMEM = "去冰，不推荐。推荐正常冰，好喝";
const char phrase56[] PROGMEM = "喝前建议搅拌一下";
const char phrase57[] PROGMEM = "建议大口大口喝";
const char phrase58[] PROGMEM = "打包还是堂食？";
const char phrase59[] PROGMEM = "MOMA燕麦奶是瑞典进口的健康奶";
const char phrase60[] PROGMEM = "这是您的小票，请收好。";
const char phrase61[] PROGMEM = "谢谢您！";
const char phrase62[] PROGMEM = "再见，欢迎您再次光临";
const char phrase63[] PROGMEM = "祝你用餐愉快";
const char phrase64[] PROGMEM = "请稍等一下";
const char phrase65[] PROGMEM = "需要等待五分钟，谢谢您";
const char phrase66[] PROGMEM = "您的订单马上就好，请稍等片刻";
const char phrase67[] PROGMEM = "您的咖啡已经准备好，请您慢用";
const char phrase68[] PROGMEM = "咖啡很热，小心烫";
const char phrase69[] PROGMEM = "咖啡是醒神的好帮手";
const char phrase70[] PROGMEM = "会有一个美好的一天";
const char phrase71[] PROGMEM = "洗手间在对面的酒店";
const char phrase72[] PROGMEM = "咖啡太热，我可以给您加点冰块";
const char phrase73[] PROGMEM = "我们还有蛋糕和面包搭配咖啡";
const char phrase74[] PROGMEM = "我们的咖啡是我们自己种的哦";
const char phrase75[] PROGMEM = "这边请";
const char phrase76[] PROGMEM = "没关系";
const char phrase77[] PROGMEM = "不用谢";
const char phrase78[] PROGMEM = "不客气";
const char phrase79[] PROGMEM = "我想想办法，看看怎样帮您";
const char phrase80[] PROGMEM = "请稍等一下，我去请示一下店长";
const char phrase81[] PROGMEM = "对不起，我没有听清楚";
const char phrase82[] PROGMEM = "请您重复一遍，好吗？";
const char phrase83[] PROGMEM = "没问题";
const char phrase84[] PROGMEM = "再见，感恩您的光临";
const char phrase85[] PROGMEM = "谢谢你，下次再来";
const char phrase86[] PROGMEM = "让您久等了，感谢您的耐心等待";
const char phrase87[] PROGMEM = "麻烦您留一下您的联系电话";
const char phrase88[] PROGMEM = "请带好随身物品";
const char phrase89[] PROGMEM = "牛奶是全脂牛奶不是低脂牛奶";
const char phrase90[] PROGMEM = "请稍候，我马上为您安排";
const char phrase91[] PROGMEM = "谢谢，欢迎您再来。";
const char phrase92[] PROGMEM = "谢谢慢走，祝您生活愉快";
const char phrase93[] PROGMEM = "请告诉我们您的意见和建议";
const char phrase94[] PROGMEM = "我们会不断改进";
const char phrase95[] PROGMEM = "我们的咖啡豆都是新鲜烘焙的";
const char phrase96[] PROGMEM = "咖啡因有助于提高注意力和记忆力";
const char phrase97[] PROGMEM = "谢谢您，祝您今天愉快！";
const char phrase98[] PROGMEM = "关注我们";
const char phrase99[] PROGMEM = "获取更多咖啡知识和独家优惠信息";
const char phrase100[] PROGMEM = "会员优惠福利";
const char phrase101[] PROGMEM = "成为我们的会员";
const char phrase102[] PROGMEM = "您将享受到更多的优惠和专属福利";
const char phrase103[] PROGMEM = "会员每月都有机会获得免费咖啡券";
const char phrase104[] PROGMEM = "在会员日";
const char phrase105[] PROGMEM = "您还可以享受到买一赠一的优惠";
const char phrase106[] PROGMEM = "参与我们的线上互动活动";
const char phrase107[] PROGMEM = "有机会赢取精美礼品";
const char phrase108[] PROGMEM = "我们的咖啡豆都是我们自己种的哦";
const char phrase109[] PROGMEM = "为给您带来最完美的咖啡";
const char phrase110[] PROGMEM = "我们坚持使用最新鲜的咖啡豆";
const char phrase111[] PROGMEM = "确保每一杯咖啡都充满生命力";
const char phrase112[] PROGMEM = "咖啡不仅味道好";
const char phrase113[] PROGMEM = "健康益处如提高注意力、抗氧化等";
const char phrase114[] PROGMEM = "咖啡采用低糖、低脂配方";
const char phrase115[] PROGMEM = "也能保持健康";
const char phrase116[] PROGMEM = "适量饮用咖啡";
const char phrase117[] PROGMEM = "可以降低患糖尿病的风险";
const char phrase118[] PROGMEM = "让您的生活更加健康";
const char phrase119[] PROGMEM = "您好，杯子给我帮您丢掉";
const char phrase120[] PROGMEM = "这个装置还在测试，请您见谅谢谢";



const char* const phrases[] PROGMEM = { "", phrase1, phrase2, phrase3, phrase4, phrase5, phrase6, phrase7, phrase8, phrase9, phrase10, phrase11, phrase12, phrase13, phrase14, phrase15, phrase16, phrase17, phrase18, phrase19, phrase20, phrase21, phrase22, phrase23, phrase24, phrase25, phrase26, phrase27, phrase28, phrase29, phrase30, phrase31, phrase32, phrase33, phrase34, phrase35, phrase36, phrase37, phrase38, phrase39, phrase40, phrase41, phrase42, phrase43, phrase44, phrase45, phrase46, phrase47, phrase48, phrase49, phrase50, phrase51, phrase52, phrase53, phrase54, phrase55, phrase56, phrase57, phrase58, phrase59, phrase60, phrase61, phrase62, phrase63, phrase64, phrase65, phrase66, phrase67, phrase68, phrase69, phrase70, phrase71, phrase72, phrase73, phrase74, phrase75, phrase76, phrase77, phrase78, phrase79, phrase80, phrase81, phrase82, phrase83, phrase84, phrase85, phrase86, phrase87, phrase88, phrase89, phrase90, phrase91, phrase92, phrase93, phrase94, phrase95, phrase96, phrase97, phrase98, phrase99, phrase100, phrase101, phrase102, phrase103, phrase104, phrase105, phrase106, phrase107, phrase108, phrase109, phrase110, phrase111, phrase112, phrase113, phrase114, phrase115, phrase116, phrase117, phrase118, phrase119, phrase120 };


*/






/* Phrases from 2024-04-10

const char phrase1[] PROGMEM = "您好，我们是无声咖啡师";
const char phrase2[] PROGMEM = "您好，欢迎光临";
const char phrase3[] PROGMEM = "很高兴为您服务";
const char phrase4[] PROGMEM = "我用AR翻译眼镜和你交流";
const char phrase5[] PROGMEM = "早上好，很高兴为您服务";
const char phrase6[] PROGMEM = "中午好，很高兴为您服务";
const char phrase7[] PROGMEM = "下午好，很高兴为您服务";
const char phrase8[] PROGMEM = "请问还有什么要求吗？";
const char phrase9[] PROGMEM = "这是咖啡店的菜单，请您过目.";  //您
const char phrase10[] PROGMEM = "对不起，我听不见，请扫码小程序";
const char phrase11[] PROGMEM = "可以扫码小程序点单";
const char phrase12[] PROGMEM = "如果你纠结点单，我来推荐好吗？";//推
const char phrase13[] PROGMEM = "这款晴天绿薄荷店里很不错";
const char phrase14[] PROGMEM = "可以试如果您不确定要喝什么咖啡";
const char phrase15[] PROGMEM = "推荐一款";
const char phrase16[] PROGMEM = "如果您喜欢浓郁的口感";
const char phrase17[] PROGMEM = "推荐摩卡咖啡";
const char phrase18[] PROGMEM = "您想点什么咖啡饮品还是面包？";
const char phrase19[] PROGMEM = "面包有三种";
const char phrase20[] PROGMEM = "可颂、葡萄卷、柠檬贝果";
const char phrase21[] PROGMEM = "面包需要加热吗";
const char phrase22[] PROGMEM = "请问您要喝咖啡还是茶？";
const char phrase23[] PROGMEM = "除了咖啡我们还有茶和果汁";
const char phrase24[] PROGMEM = "还有喜欢吗？";
const char phrase25[] PROGMEM = "谢谢光临";
const char phrase26[] PROGMEM = "需要打包吗";
const char phrase27[] PROGMEM = "奈娃爱您!";
const char phrase28[] PROGMEM = "爪爪爱您!";
const char phrase29[] PROGMEM = "我能帮您推荐吗";
const char phrase30[] PROGMEM = "绿柠茶冰冰";
const char phrase31[] PROGMEM = "菠莓茶冰冰";
const char phrase32[] PROGMEM = "日落躺岛";
const char phrase33[] PROGMEM = "星愿湾椰椰拿铁，推荐全冰"; //is the space？
const char phrase34[] PROGMEM = "小镇燕麦拿铁";
const char phrase35[] PROGMEM = "晴空山巴旦木拿铁";
const char phrase36[] PROGMEM = "晴空山核桃拿铁";
const char phrase37[] PROGMEM = "橙咖橘子海，有咖啡"; 
const char phrase38[] PROGMEM = "整块蜂巢麦奇朵，有一颗蜂巢，好喝"; //the second comma？
const char phrase39[] PROGMEM = "晴天薄荷绿";
const char phrase40[] PROGMEM = "不喜欢咖啡，可以考虑奶猪古力"; //fourth char after comma？
const char phrase41[] PROGMEM = "奶猪燕麦";
const char phrase42[] PROGMEM = "推荐三杯小奈咖";
const char phrase43[] PROGMEM = "小岛绿薄荷";
const char phrase44[] PROGMEM = "吵够了莓";
const char phrase45[] PROGMEM = "头上有点绿";
const char phrase46[] PROGMEM = "挚爱冠军拿铁";
const char phrase47[] PROGMEM = "绝美美式";
const char phrase48[] PROGMEM = "小美美式";
const char phrase49[] PROGMEM = "热还是冷？";
const char phrase50[] PROGMEM = "温热？";
const char phrase51[] PROGMEM = "您需要加糖吗？";
const char phrase52[] PROGMEM = "正常冰？少冰？去冰？";
const char phrase53[] PROGMEM = "少糖？正常糖？无糖？";
const char phrase54[] PROGMEM = "无糖，不推荐.推荐正常"; //before the period
const char phrase55[] PROGMEM = "去冰，不推荐.推荐正常冰，好喝"; //before the period
const char phrase56[] PROGMEM = "喝前建议搅拌一下";
const char phrase57[] PROGMEM = "建议大口大口喝";
const char phrase58[] PROGMEM = "打包还是堂食？";
const char phrase59[] PROGMEM = "MOMA燕麦奶是健康奶";
const char phrase60[] PROGMEM = "这是您的小票，请收好.";
const char phrase61[] PROGMEM = "谢谢您!";
const char phrase62[] PROGMEM = "再见，欢迎您再次光临";
const char phrase63[] PROGMEM = "祝你用餐愉快~";
const char phrase64[] PROGMEM = "请稍等一下";
const char phrase65[] PROGMEM = "需要等待五分钟，谢谢您"; //numbers
const char phrase66[] PROGMEM = "您的订单马上就好，请稍等片刻";
const char phrase67[] PROGMEM = "您的咖啡已经准备好，请您慢用";
const char phrase68[] PROGMEM = "咖啡很热，小心烫";
const char phrase69[] PROGMEM = "咖啡是醒神的好帮手";
const char phrase70[] PROGMEM = "会有一个美好的一天.";
const char phrase71[] PROGMEM = "洗手间在对面的酒店";
const char phrase72[] PROGMEM = "咖啡太热，我可以给您加点冰块";
const char phrase73[] PROGMEM = "我们还有蛋糕和面包搭配咖啡";
const char phrase74[] PROGMEM = "我们的咖啡是我们自己种的哦";
const char phrase75[] PROGMEM = "这边请.";
const char phrase76[] PROGMEM = "没关系";
const char phrase77[] PROGMEM = "不用谢";
const char phrase78[] PROGMEM = "不客气";
const char phrase79[] PROGMEM = "我想想办法，看看怎样帮您";
const char phrase80[] PROGMEM = "请稍等一下，我去请示一下店长";
const char phrase81[] PROGMEM = "对不起，我没有听清楚";
const char phrase82[] PROGMEM = "请您重复一遍，好吗？";
const char phrase83[] PROGMEM = "没问题";
const char phrase84[] PROGMEM = "再见";
const char phrase85[] PROGMEM = "谢谢你，下次再来";
const char phrase86[] PROGMEM = "让您久等了，感谢您的耐心等待";
const char phrase87[] PROGMEM = "麻烦您留一下您的联系电话";
const char phrase88[] PROGMEM = "请带好随身物品";
const char phrase89[] PROGMEM = "牛奶是全脂牛奶，不是低脂牛奶";
const char phrase90[] PROGMEM = "请稍候，我马上为您安排";
const char phrase91[] PROGMEM = "谢谢，欢迎您再来.";
const char phrase92[] PROGMEM = "谢谢慢走，祝您生活愉快";
const char phrase93[] PROGMEM = "请告诉我们您的意见和建议";
const char phrase94[] PROGMEM = "我们会不断改进.";
const char phrase95[] PROGMEM = "我们的咖啡豆都是新鲜烘焙的";
const char phrase96[] PROGMEM = "咖啡因有助于提高注意力和记忆力";
const char phrase97[] PROGMEM = "谢谢您，祝您今天愉快!";
const char phrase98[] PROGMEM = "关注我们";
const char phrase99[] PROGMEM = "获取更多咖啡知识和独家优惠信息";
const char phrase100[] PROGMEM = "会员优惠福利";
const char phrase101[] PROGMEM = "成为我们的会员";
const char phrase102[] PROGMEM = "您将享受到更多的优惠和专属福利";
const char phrase103[] PROGMEM = "会员每月都有机会获得免费咖啡券";
const char phrase104[] PROGMEM = "在会员日";
const char phrase105[] PROGMEM = "您还可以享受到买一赠一的超值优惠";
const char phrase106[] PROGMEM = "参与我们的线上互动活动";
const char phrase107[] PROGMEM = "有机会赢取精美礼品";
const char phrase108[] PROGMEM = "从采摘到杯中";
const char phrase109[] PROGMEM = "为给您带来最完美的咖啡";
const char phrase110[] PROGMEM = "我们坚持使用最新鲜的咖啡豆";
const char phrase111[] PROGMEM = "确保每一杯咖啡都充满生命力";
const char phrase112[] PROGMEM = "咖啡不仅味道好";
const char phrase113[] PROGMEM = "健康益处如提高注意力、抗氧化等";
const char phrase114[] PROGMEM = "咖啡采用低糖、低脂配方";
const char phrase115[] PROGMEM = "也能保持健康";
const char phrase116[] PROGMEM = "适量饮用咖啡";
const char phrase117[] PROGMEM = "可以降低患糖尿病的风险";
const char phrase118[] PROGMEM = "让您的生活更加健康";
const char phrase119[] PROGMEM = "您好，杯子给我帮您丢掉";
const char phrase120[] PROGMEM = "这个装置还在测试，请您见谅谢谢";

const char *const phrases[] PROGMEM = { phrase1, phrase2, phrase3, phrase4, phrase5, phrase6, phrase7, phrase8, phrase9, phrase10, phrase11, phrase12, phrase13, phrase14, phrase15, phrase16, phrase17, phrase18, phrase19, phrase20,
                                        phrase21, phrase22, phrase23, phrase24, phrase25, phrase26, phrase27, phrase28, phrase29, phrase30, phrase31, phrase32, phrase33, phrase34, phrase35, phrase36, phrase37, phrase38, phrase39, phrase40,
                                        phrase41, phrase42, phrase43, phrase44, phrase45, phrase46, phrase47, phrase48, phrase49, phrase50, phrase51, phrase52, phrase53, phrase54, phrase55, phrase56, phrase57, phrase58, phrase59, phrase60, phrase61,
                                        phrase62, phrase63, phrase64, phrase65, phrase66, phrase67, phrase68, phrase69, phrase70, phrase71, phrase72, phrase73, phrase74, phrase75, phrase76, phrase77, phrase78, phrase79, phrase80,
                                        phrase81, phrase82, phrase83, phrase84, phrase85, phrase86, phrase87, phrase88, phrase89, phrase90, phrase91, phrase92, phrase93, phrase94, phrase95, phrase96, phrase97, phrase98, phrase99, phrase100,
                                        phrase101, phrase102, phrase103, phrase104, phrase105, phrase106, phrase107, phrase108, phrase109, phrase110, phrase111, phrase112, phrase113, phrase114, phrase115, phrase116, phrase117, phrase118, phrase119, phrase120 };



*/


/*

const char phrase1[] PROGMEM = "This sentence is a test"; // ���ã���������������ʦ";
const char phrase2[] PROGMEM = "Also a test sentence";    //"���ã���ӭ����";
const char phrase3[] PROGMEM = "�ܸ���Ϊ������";
const char phrase4[] PROGMEM = "����AR�����۾����㽻��";
const char phrase5[] PROGMEM = "���Ϻ�，�ܸ���Ϊ������";
const char phrase6[] PROGMEM = "�����，�ܸ���Ϊ������";
const char phrase7[] PROGMEM = "�����，�ܸ���Ϊ������";
const char phrase8[] PROGMEM = "���ʻ���ʲôҪ����？";
const char phrase9[] PROGMEM = "���ǿ��ȵ�Ĳ˵���������Ŀ��";
const char phrase10[] PROGMEM = "�Բ���������������ɨ��С����";
const char phrase11[] PROGMEM = "����ɨ��С����㵥";
const char phrase12[] PROGMEM = "��������㵥�������Ƽ�����";
const char phrase13[] PROGMEM = "��������̱��ɵ���ܲ���";
const char phrase14[] PROGMEM = "�������������ȷ��Ҫ��ʲô����";
const char phrase15[] PROGMEM = "�Ƽ�һ��";
const char phrase16[] PROGMEM = "�����ϲ��Ũ���Ŀڸ�";
const char phrase17[] PROGMEM = "�Ƽ�Ħ������";
const char phrase18[] PROGMEM = "�����ʲô������Ʒ���������";
const char phrase19[] PROGMEM = "���������";
const char phrase20[] PROGMEM = "���̡����Ѿ������ʱ���";
const char phrase21[] PROGMEM = "�����Ҫ������";
const char phrase22[] PROGMEM = "������Ҫ�ȿ��Ȼ��ǲ裿";
const char phrase23[] PROGMEM = "���˿������ǻ��в�͹�֭";
const char phrase24[] PROGMEM = "����ϲ����";
const char phrase25[] PROGMEM = "лл����";
const char phrase26[] PROGMEM = "��Ҫ�����";
const char phrase27[] PROGMEM = "���ް�����";
const char phrase28[] PROGMEM = "צצ������";
const char phrase29[] PROGMEM = "���ܰ����Ƽ���";
const char phrase30[] PROGMEM = "���������";
const char phrase31[] PROGMEM = "��ݮ�����";
const char phrase32[] PROGMEM = "�����ɵ�";
const char phrase33[] PROGMEM = "��Ը��ҬҬ���� �Ƽ�ȫ��";
const char phrase34[] PROGMEM = "С����������";
const char phrase35[] PROGMEM = "���ɽ�͵�ľ����";
const char phrase36[] PROGMEM = "���ɽ��������";
const char phrase37[] PROGMEM = "�ȿ����Ӻ� �п���";
const char phrase38[] PROGMEM = "����䳲����䣬��һ�ŷ䳲���ú�";
const char phrase39[] PROGMEM = "���챡����";
const char phrase40[] PROGMEM = "��ϲ�����ȣ����Կ�����������";
const char phrase41[] PROGMEM = "��������";
const char phrase42[] PROGMEM = "�Ƽ�����С�ο�";
const char phrase43[] PROGMEM = "С���̱���";
const char phrase44[] PROGMEM = "������ݮ";
const char phrase45[] PROGMEM = "ͷ���е���";
const char phrase46[] PROGMEM = "ֿ���ھ�����";
const char phrase47[] PROGMEM = "������ʽ ";
const char phrase48[] PROGMEM = "С����ʽ";
const char phrase49[] PROGMEM = "�Ȼ����䣿";
const char phrase50[] PROGMEM = "���ȣ�";
const char phrase51[] PROGMEM = "����Ҫ������";
const char phrase52[] PROGMEM = "���������ٱ���ȥ����";
const char phrase53[] PROGMEM = "���ǣ������ǣ����ǣ�";
const char phrase54[] PROGMEM = "���ǣ����Ƽ����Ƽ�����";
const char phrase55[] PROGMEM = "ȥ�������Ƽ����Ƽ����������ú�";
const char phrase56[] PROGMEM = "��ǰ�������һ��";
const char phrase57[] PROGMEM = "�����ڴ�ں�";
const char phrase58[] PROGMEM = "���������ʳ��";
const char phrase59[] PROGMEM = "MOMA�������ǽ�����";
const char phrase60[] PROGMEM = "��������СƱ�����պá�";
const char phrase61[] PROGMEM = "лл����";
const char phrase62[] PROGMEM = "�ټ�����ӭ���ٴι���";
const char phrase63[] PROGMEM = "ף���ò����~";
const char phrase64[] PROGMEM = "���Ե�һ��";
const char phrase65[] PROGMEM = "��Ҫ�ȴ�5���ӣ�лл��";
const char phrase66[] PROGMEM = ".���Ķ������Ͼͺã����Ե�Ƭ��";
const char phrase67[] PROGMEM = "���Ŀ����Ѿ�׼���ã���������";
const char phrase68[] PROGMEM = "���Ⱥ��ȣ�С����";
const char phrase69[] PROGMEM = "����������ĺð���";
const char phrase70[] PROGMEM = "����һ�����õ�һ�졣";
const char phrase71[] PROGMEM = "ϴ�ּ��ڶ���ľƵ�";
const char phrase72[] PROGMEM = "����̫�ȣ��ҿ��Ը����ӵ����";
const char phrase73[] PROGMEM = "���ǻ��е����������俧��";
const char phrase74[] PROGMEM = "���ǵĿ����������Լ��ֵ�Ŷ";
const char phrase75[] PROGMEM = "����롣";
const char phrase76[] PROGMEM = "û��ϵ";
const char phrase77[] PROGMEM = "����л";
const char phrase78[] PROGMEM = "������";
const char phrase79[] PROGMEM = "������취��������������";
const char phrase80[] PROGMEM = "���Ե�һ�£���ȥ��ʾһ�µ곤";
const char phrase81[] PROGMEM = "�Բ�����û�������";
const char phrase82[] PROGMEM = "�����ظ�һ�飬����";
const char phrase83[] PROGMEM = "û����";
const char phrase84[] PROGMEM = "�ټ�";
const char phrase85[] PROGMEM = "лл�㣬�´�����";
const char phrase86[] PROGMEM = "�����õ��ˣ���л�������ĵȴ�";
const char phrase87[] PROGMEM = "�鷳����һ��������ϵ�绰";
const char phrase88[] PROGMEM = "�����������Ʒ";
const char phrase89[] PROGMEM = "ţ����ȫ֬ţ�� ���ǵ�֬ţ��";
const char phrase90[] PROGMEM = "���Ժ�������Ϊ������";
const char phrase91[] PROGMEM = "лл����ӭ��������";
const char phrase92[] PROGMEM = "лл���ߣ�ף���������";
const char phrase93[] PROGMEM = "�����������������ͽ���";
const char phrase94[] PROGMEM = "���ǻ᲻�ϸĽ���";
const char phrase95[] PROGMEM = "���ǵĿ��ȶ��������ʺ決��";
const char phrase96[] PROGMEM = "���������������ע�����ͼ�����";
const char phrase97[] PROGMEM = "лл����ף��������죡";
const char phrase98[] PROGMEM = "��ע����";
const char phrase99[] PROGMEM = "��ȡ���࿧��֪ʶ�Ͷ����Ż���Ϣ";
const char phrase100[] PROGMEM = "��Ա�Żݸ���";
const char phrase101[] PROGMEM = "��Ϊ���ǵĻ�Ա";
const char phrase102[] PROGMEM = "�������ܵ�������Żݺ�ר������";
const char phrase103[] PROGMEM = "��Աÿ�¶��л�������ѿ���ȯ";
const char phrase104[] PROGMEM = "�ڻ�Ա��";
const char phrase105[] PROGMEM = "�����������ܵ���һ��һ�ĳ�ֵ�Ż�";
const char phrase106[] PROGMEM = "�������ǵ����ϻ����";
const char phrase107[] PROGMEM = "�л���Ӯȡ������Ʒ";
const char phrase108[] PROGMEM = "�Ӳ�ժ������";
const char phrase109[] PROGMEM = "Ϊ���������������Ŀ���";
const char phrase110[] PROGMEM = "���Ǽ��ʹ�������ʵĿ��ȶ�";
const char phrase111[] PROGMEM = "ȷ��ÿһ�����ȶ�����������";
const char phrase112[] PROGMEM = "���Ȳ���ζ����";
const char phrase113[] PROGMEM = "�����洦�����ע��������������";
const char phrase114[] PROGMEM = "���Ȳ��õ��ǡ���֬�䷽";
const char phrase115[] PROGMEM = "Ҳ�ܱ��ֽ���";
const char phrase116[] PROGMEM = "�������ÿ���";
const char phrase117[] PROGMEM = "���Խ��ͻ����򲡵ķ���";
const char phrase118[] PROGMEM = "������������ӽ���";
const char phrase119[] PROGMEM = "���ã����Ӹ��Ұ�������";
const char phrase120[] PROGMEM = "���װ�û��ڲ��ԣ���������лл";

const char *const phrases[] PROGMEM = {phrase1， phrase2， phrase3， phrase4， phrase5， phrase6， phrase7， phrase8， phrase9， phrase10， phrase11， phrase12， phrase13， phrase14， phrase15， phrase16， phrase17， phrase18， phrase19， phrase20，
                                       phrase21， phrase22， phrase23， phrase24， phrase25， phrase26， phrase27， phrase28， phrase29， phrase30， phrase31， phrase32， phrase33， phrase34， phrase35， phrase36， phrase37， phrase38， phrase39， phrase40，
                                       phrase41， phrase42， phrase43， phrase44， phrase45， phrase46， phrase47， phrase48， phrase49， phrase50， phrase51， phrase52， phrase53， phrase54， phrase55， phrase56， phrase57， phrase58， phrase59， phrase60， phrase61，
                                       phrase62， phrase63， phrase64， phrase65， phrase66， phrase67， phrase68， phrase69， phrase70， phrase71， phrase72， phrase73， phrase74， phrase75， phrase76， phrase77， phrase78， phrase79， phrase80，
                                       phrase81， phrase82， phrase83， phrase84， phrase85， phrase86， phrase87， phrase88， phrase89， phrase90， phrase91， phrase92， phrase93， phrase94， phrase95， phrase96， phrase97， phrase98， phrase99， phrase100，
                                       phrase101， phrase102， phrase103， phrase104， phrase105， phrase106， phrase107， phrase108， phrase109， phrase110， phrase111， phrase112， phrase113， phrase114， phrase115， phrase116， phrase117， phrase118， phrase119， phrase120};


                                       */
